### ISSUE TITLE
SEGV running binary - how to debug further?

### ISSUE THREAD

**Issue by tmm1** [termux/proot#107]
I'm trying to run headless chromium via proot. It works on `arm64-v8a` devices, but on `armeabi-v7a` I'm getting a segfault:

```
# PROOT_NO_SECCOMP=1 LD_PRELOAD= proot --link2symlink -0 -r $PREFIX/share/TermuxAlpine/ -b /dev -b /sys -b /proc -w / /usr/lib/chromium/chrome --version
proot info: vpid 1: terminated with signal 11
```

```
# startalpine
[root@localhost home]# /usr/lib/chromium/chrome --version
Segmentation fault
```

```
proot info: exe = /usr/lib/chromium/chrome
proot info: argv = /usr/lib/chromium/chrome --version
proot info: initial cwd = /
proot info: verbose level = 999
proot info: pid 28492: access to "/dev/pts/3" (fd 0) won't be translated until closed
proot info: pid 28492: access to "/dev/pts/3" (fd 1) won't be translated until closed
proot info: pid 28492: access to "/dev/pts/3" (fd 2) won't be translated until closed
proot info: pid 28492: access to "/proc/28492/fd" (fd 3) won't be translated until closed
proot info: vpid 1: sysenter start: execve(0xec91d0d0, 0xff820660, 0xff82066c, 0x2f, 0xec910030, 0xff820660) = 0xec91d0d0 [0xff81e550, 0]
proot info: vpid 1: translate("/" + "/usr/lib/chromium/chrome")
proot info: vpid 1:          -> "/data/data/com.termux/files/usr/share/TermuxAlpine/usr/lib/chromium/chrome"
proot info: vpid 1: translate("/" + "/lib/ld-musl-armhf.so.1")
proot info: vpid 1:          -> "/data/data/com.termux/files/usr/share/TermuxAlpine/lib/ld-musl-armhf.so.1"
proot info: vpid 1: sysenter end: execve(0xff81e51b, 0xff820660, 0xff82066c, 0x2f, 0xec910030, 0xff820660) = 0xff81e51b [0xff81e51b, 0]
proot info: vpid 1: sysexit start: restart_syscall(0x0, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x0 [0xff8143f0, 0]
proot info: vpid 1: sysexit end: restart_syscall(0xff8142fc, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xff8142fc [0xff8142fc, 0]
proot info: vpid 1: sysenter start: open(0xff8143bc, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xff8143bc [0xff8142f8, 0]
proot info: vpid 1: translate("/" + "/usr/lib/chromium/chrome")
proot info: vpid 1:          -> "/data/data/com.termux/files/usr/share/TermuxAlpine/usr/lib/chromium/chrome"
proot info: vpid 1: sysenter end: open(0xff8142ad, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xff8142ad [0xff8142ad, 0]
proot info: vpid 1: sysexit start: open(0x3, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x3 [0xff8142ad, 0]
proot info: vpid 1: sysexit end: open(0x3, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x3 [0xff8142f8, 0]
proot info: vpid 1: sysenter start: mmap2(0xf000000, 0x595e000, 0x5, 0x12, 0x3, 0x0) = 0xf000000 [0xff8142f8, 0]
proot info: vpid 1: sysenter end: mmap2(0xf000000, 0x595e000, 0x5, 0x12, 0x3, 0x0) = 0xf000000 [0xff8142f8, 0]
proot info: vpid 1: sysexit start: mmap2(0xf000000, 0x595e000, 0x5, 0x12, 0x3, 0x0) = 0xf000000 [0xff8142f8, 0]
proot info: vpid 1: sysexit end: mmap2(0xf000000, 0x595e000, 0x5, 0x12, 0x3, 0x0) = 0xf000000 [0xff8142f8, 0]
proot info: vpid 1: translate("/" + "/usr/lib/chromium/chrome")
proot info: vpid 1:          -> "/data/data/com.termux/files/usr/share/TermuxAlpine/usr/lib/chromium/chrome"
proot info: vpid 1: terminated with signal 11
```

**Comment by michalbednarski** [comment]
Looks like loaded binary mapping has clashed with loader ([loader address is defined in `arch.h`](https://github.com/termux/proot/blob/b9588b1edff5069118c50f2f9b19397fce39f5c7/src/arch.h#L104), this value [is referenced from `GNUMakefile`](https://github.com/termux/proot/blob/b9588b1edff5069118c50f2f9b19397fce39f5c7/src/GNUmakefile#L202)).

Probably either `LOADER_ADDRESS` should be raised or `EXEC_PIC_ADDRESS` should be lowered, but I don't know what these values should actually be.

**Comment by tmm1** [comment]
Thanks! Really appreciate the pointer.

I see the `EXEC_PIC_ADDRESS` being mmap'd in the verbose output above, but no indication of `LOADER_ADDRESS`. Did you see something in there that suggested overlap, or just a hunch based on the segv that the binary was being corrupted?

Either way, you were correct and the following works for me now:

```diff
--- a/src/arch.h
+++ b/src/arch.h
@@ -101,7 +101,7 @@ typedef unsigned char byte_t;
     #define OFFSETOF_STAT_GID_32 0
     #define EM_ARM 40

-    #define LOADER_ADDRESS 0x10000000
+    #define LOADER_ADDRESS 0x20000000

     #define EXEC_PIC_ADDRESS   0x0f000000
     #define INTERP_PIC_ADDRESS 0x1f000000
```

Not sure if this is something that should be merged, or if there would be other unintended consequences. Now that the binary runs maybe I can look at `/proc/pid/maps` and see where the overlap was and how much extra space is actually needed..

**Comment by tmm1** [comment]
Spent a ton of time trying to reproduce this today. I kept trying to add a test I expected would fail, but it wasn't failing even on the same setup.

Finally I discovered a subtle bug in my app's calling code:

```go
err := chromedp.Run(ctx)
if err, ok := err.(*exec.Error); ok && err.Err == exec.ErrNotFound {
    return fmt.Errorf("chrome was not found on your system")
} else if err != nil {
    return err
}
err = chromedp.Run(ctx, ....)
```

Apparently the `if` statement reusing `err` overwrites the value in the `!ok` case, causing the `else` to fail and then `chromedp.Run` is called again and hangs forever.

The bug can be fixed in my app by renaming `err` in the if statement, however I think chromedp should also complain loudly if the context is reused like this? Here's a failing test for that:

```diff
diff --git a/allocate_test.go b/allocate_test.go
index 3610c0f..15b4795 100644
--- a/allocate_test.go
+++ b/allocate_test.go
@@ -104,6 +104,29 @@ func TestExecAllocatorKillBrowser(t *testing.T) {
        }
 }

+func TestExecAllocatorFailReuse(t *testing.T) {
+       t.Parallel()
+
+       // To ensure we don't actually fire any Chrome processes.
+       allocCtx, _ := NewExecAllocator(context.Background(),
+               ExecPath("testdata/chromecrash.sh"))
+
+       ctx, cancel := NewContext(allocCtx)
+       defer cancel()
+       if err := Run(ctx); err == nil {
+               t.Fatalf("expected err but got nil")
+       } else {
+               t.Logf("err1: %v", err)
+       }
+
+       // Try to use expired context again
+       if err := Run(ctx); err == nil {
+               t.Fatalf("expected err but got nil")
+       } else {
+               t.Logf("err2: %v", err)
+       }
+}
+
 func TestSkipNewContext(t *testing.T) {
        t.Parallel()

diff --git a/testdata/chromecrash.sh b/testdata/chromecrash.sh
new file mode 100755
index 0000000..7f7e33d
--- /dev/null
+++ b/testdata/chromecrash.sh
@@ -0,0 +1,2 @@
+#!/bin/sh
+exit 11
```

which reproduces the hang readily on my mac:

```shell
$ go test -v ./ -run TestExecAllocatorFailReuse
=== RUN   TestExecAllocatorFailReuse
=== PAUSE TestExecAllocatorFailReuse
=== CONT  TestExecAllocatorFailReuse
    TestExecAllocatorFailReuse: allocate_test.go:119: err1: chrome failed to start:
^\SIGQUIT: quit
PC=0x7fff70108882 m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x1a612c8, 0x1a61288, 0x0)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/sys_darwin.go:390 +0x39
runtime.semasleep(0xffffffffffffffff, 0x7ffeefbff570)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/os_darwin.go:63 +0x85
runtime.notesleep(0x1a61088)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/lock_sema.go:173 +0xe0
runtime.stopm()
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:1828 +0xc0
runtime.findrunnable(0xc000044000, 0x0)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:2360 +0xa0d
runtime.schedule()
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:2520 +0x2fc
runtime.park_m(0xc0001a2180)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x10658c6)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc0000c1200)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:956 +0x238
testing.tRunner(0xc0000c1200, 0xc00006fd78)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:995 +0x10b
testing.runTests(0xc00000e6e0, 0x1a5a180, 0x5d, 0x5d, 0x0)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1282 +0x2a7
testing.(*M).Run(0xc000190000, 0x0)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1199 +0x15f
github.com/chromedp/chromedp.TestMain(0xc000190000)
	/Users/tmm1/fancybits/chromedp/chromedp_test.go:82 +0x138
main.main()
	_testmain.go:252 +0x135

goroutine 6 [select]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate(0xc0000322d0, 0x16a2200, 0xc00019e090, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tmm1/fancybits/chromedp/allocate.go:190 +0x96a
github.com/chromedp/chromedp.Run(0x16a2200, 0xc00019e090, 0x0, 0x0, 0x0, 0x1, 0xc0000738f0)
	/Users/tmm1/fancybits/chromedp/chromedp.go:228 +0x209
github.com/chromedp/chromedp.TestExecAllocatorFailReuse(0xc0000c1320)
	/Users/tmm1/fancybits/chromedp/allocate_test.go:123 +0x1c2
testing.tRunner(0xc0000c1320, 0x15fa428)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1042 +0x357

goroutine 7 [chan receive]:
testing.runTests.func1.1(0xc0000c1200)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1289 +0x3b
created by testing.runTests.func1
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1289 +0xac

goroutine 8 [chan receive]:
github.com/chromedp/chromedp.NewContext.func1(0x16a2200, 0xc00019e090, 0xc0000b04d0)
	/Users/tmm1/fancybits/chromedp/chromedp.go:130 +0x78
created by github.com/chromedp/chromedp.NewContext
	/Users/tmm1/fancybits/chromedp/chromedp.go:129 +0x22a

goroutine 9 [select]:
os/exec.(*Cmd).Start.func2(0xc0000ce420)
	/usr/local/Cellar/go/1.14.3/libexec/src/os/exec/exec.go:449 +0xc4
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.14.3/libexec/src/os/exec/exec.go:448 +0x6d0

goroutine 10 [chan receive]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2(0x16a2200, 0xc00019e090, 0xc0000ce420, 0xc0000ce401, 0xc0000907e0, 0x60, 0xc0000b04d0, 0xc0000322d0)
	/Users/tmm1/fancybits/chromedp/allocate.go:200 +0x4c
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
	/Users/tmm1/fancybits/chromedp/allocate.go:199 +0xa2d

goroutine 12 [select]:
os/exec.(*Cmd).Start.func2(0xc0000ce580)
	/usr/local/Cellar/go/1.14.3/libexec/src/os/exec/exec.go:449 +0xc4
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.14.3/libexec/src/os/exec/exec.go:448 +0x6d0

rax    0x104
rbx    0x2
rcx    0x7ffeefbff398
rdx    0x200
rdi    0x1a612c8
rsi    0x30100000400
rbp    0x7ffeefbff430
rsp    0x7ffeefbff398
r8     0x0
r9     0xa0
r10    0x0
r11    0x202
r12    0x1a612c8
r13    0x16
r14    0x30100000400
r15    0x7365dc0
rip    0x7fff70108882
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
FAIL	github.com/chromedp/chromedp	1.787s
```

**Comment by tmm1** [comment]
I discovered there is an old WIP branch upstream that tries to remove `LOADER_ADDRESS`: https://github.com/proot-me/proot/compare/position_independant

**Comment by WMCB-Tech** [comment]
Hi, i pointed to this issue where i needed to run Chromium on 32-bit environment, somehow running chromium by setting `LOADER_ADDRESS` to `0x20000000` works so far i didn't get any strange side effects from time to time

I guess it's time that `LOADER_ADDRESS` should be set to `0x20000000`?

**Comment by ZhymabekRoman** [comment]
@WMCB-Tech, may be best to apply changes from the position_independant branch to the Termux proot repository?

**Comment by WMCB-Tech** [comment]
just to be safe then probably,
