### ISSUE TITLE
[Feature request] Termux's shm support.

### ISSUE THREAD

**Issue by twaik** [termux/proot#271]
Hi. I am writing new termux-x11 version which will use embedded X server. That means it will be impossible to use Xvfb or Xwayland in proot container so proot-distro users will not be able to use any program which requires MIT-SHM support.

MIT-SHM requires both server (which will run in android's JVM) and clients (in our case in proot'ed environment) to have the same sysv ipc mechanisms. I know that it is complicated because of syscall chaining, but maybe there is some way to make proot use termux's ipc implementation?

For some reason termux-x11 can not be started in proot (for some reason `app_process` can not find required files) so I can not start it in container.

Thank you for your hard work.

**Comment by twaik** [comment]
It simply prints `Killed` to stderr. 
<details>
<summary>logcat</summary>

```
04-21 10:21:21.459 29632 29632 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
04-21 10:21:22.199 29632 29632 I AndroidRuntime: Using default boot image
04-21 10:21:22.203 29632 29632 I AndroidRuntime: Leaving lock profiling enabled
04-21 10:21:22.215 29632 29632 W libc    : Access denied finding property "odsign.verification.success"
04-21 10:21:22.248 29632 29632 D AndroidRuntime: addProductProperty: pBrand1 is not null
04-21 10:21:22.253 29632 29632 D AndroidRuntime: addProductProperty: not brand or 7
04-21 10:21:22.425 29632 29632 W app_process: ART APEX data files are untrusted.
04-21 10:21:22.444 29632 29632 I app_process: Using CollectorTypeCC GC.
04-21 10:21:31.464 29632 29632 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
04-21 10:21:31.478 29632 29632 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
04-21 10:21:31.888 29632 29632 W ziparchive: Unable to open '/data/data/com.termux/files/usr/libexec/termux-x11/loader.dm': No such file or directory
04-21 10:21:32.274 29632 29632 E SemDvfsManager_JNI: SemDvfsManager: registerfunction enter
04-21 10:21:32.285 29632 29632 E SemAffinityControl: SemAffinityControl: registerfunction enter
04-21 10:21:32.988 29632 29632 D AndroidRuntime: Calling main entry com.termux.x11.Loader
04-21 10:21:33.013 29632 29632 I Termux:X11 loader: started
04-21 10:21:33.058 29632 29632 W libc    : Access denied finding property "qemu.sf.lcd_density"
04-21 10:21:33.068 29632 29632 W libc    : Access denied finding property "qemu.sf.lcd_density"
04-21 10:21:34.904 29632 29632 W app_process: unable to execute idmap2: Permission denied
04-21 10:21:34.908 29632 29632 W OverlayConfig: 'idmap2 create-multiple' failed: no mutable="false" overlays targeting "android" will be loaded
04-21 10:21:34.918 29632 29632 W libc    : Access denied finding property "ro.vendor.mtk_model"
04-21 10:21:35.115 29632 29632 I SemTelecomManager: hasSamsungTelecomSystemFeature : true
04-21 10:21:35.272 29632 29632 E SystemServiceRegistry: systemservice inputdev:true
04-21 10:21:36.535 29632 29632 D SecIpmManagerFrameworkInitializer:  initial
04-21 10:21:36.648 29632 29632 I Typeface: Preloading /system/fonts/Roboto-Regular.ttf
04-21 10:21:36.669 29632 29632 I Typeface: Preloading /system/fonts/RobotoStatic-Regular.ttf
04-21 10:21:38.773 29632 29632 I Termux:X11 loader: loading /data/app/~~-yZV8Mu0AEhjsqToRXO0iw==/com.termux.x11-Htmzwd08R78w6ClHfGDhTA==/base.apk of com.termux.x11 application
04-21 10:21:38.781 29632 29632 W System  : ClassLoader referenced unknown path: /data/app/~~-yZV8Mu0AEhjsqToRXO0iw==/com.termux.x11-Htmzwd08R78w6ClHfGDhTA==/base.apk
04-21 10:21:38.806 29632 29632 D AndroidRuntime: Shutting down VM
04-21 10:21:38.815 29632 29632 E AndroidRuntime: FATAL EXCEPTION: main
04-21 10:21:38.815 29632 29632 E AndroidRuntime: PID: 29632
04-21 10:21:38.815 29632 29632 E AndroidRuntime: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.termux.x11.CmdEntryPoint
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	at com.termux.x11.Loader.main(Loader.java:63)
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
04-21 10:21:38.815 29632 29632 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.termux.x11.CmdEntryPoint
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:454)
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	at com.termux.x11.Loader.main(Loader.java:59)
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	... 2 more
04-21 10:21:38.815 29632 29632 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.termux.x11.CmdEntryPoint
04-21 10:21:38.815 29632 29632 E AndroidRuntime: 	... 5 more
04-21 10:21:38.827 29632 29632 E AndroidRuntime: Error reporting crash
04-21 10:21:38.827 29632 29632 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:653)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:427)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:202)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:5212)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:5209)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:5200)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:176)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-21 10:21:38.827 29632 29632 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
04-21 10:21:38.834 29632 29632 I Process : Sending signal. PID: 29632 SIG: 9
```
</details>

[strace_log.txt](https://github.com/termux/proot/files/11293298/strace_log.txt)

It looks like it simply can not access path to apk (in `/data/app`) it gets from PackageManager API.

**Comment by twaik** [comment]
Is there a way to detect proot? When I tried to use `syscall(SYS_shmat) ` my application was killed by seccomp so I think I need somehow detect proot to enable using sysvipc syscalls only in proot.

**Comment by twaik** [comment]
And there is one more question. How to make proot use single namespace for all the invocations of proot (mentioned [here](https://github.com/termux/proot/issues/258#issuecomment-1454574959))?

**Comment by michalbednarski** [comment]
> When I tried to use `syscall(SYS_shmat)` my application was killed by seccomp

In that case you can detect that by registering signal handler for `SIGSYS` or checking in child process

Another way is used by `systemd-detect-virt`, which detects `proot` by [looking for `TracerPid` in `/proc/self/status` and checking if that process with name starting with `"proot"`](https://github.com/systemd/systemd/blob/aab896e2135362ab126830c73284d4af0baad88a/src/basic/virt.c#L691-L716)

Note that you can also be under `proot` without `--sysvipc`, in which case `syscall(SYS_shmat)` will return `-ENOSYS` without raising signal

> make proot use single namespace for all the invocations of proot

There currently isn't such option as this namespacing behaviour is just effect of that shm status is stored within `proot` process, there isn't client-server (The `proot --shm-helper` process stores shared memory file descriptors, however all bookkeeping is in main `proot` process)

Probably it'd make more sense to use `libandroid-shmem`'s server (or do you use something else?), than attempting to make my implementation start own server, although for that probably I'd need additional helper binary from `libandroid-shmem` side (as currently with `libandroid-shmem` runs server in whatever process requested allocation and I would like to avoid pulling `libandroid-shmem` server into `proot` and also I'd need something that would provide shm metadata and file descriptors instead of directly mapping them)

Also in that case `sem` and `msg` would still be separate namespaces

It might also be possible to just use `libandroid-shmem` inside `proot`, although don't really know if current ports work

**Comment by twaik** [comment]
It seems like proot uses file descriptors for shareable memory fragments. What will happen in the case if we create shmat-like function for obtaining file descriptor of shared memory fragment? I mean can you make proot use it?
In this case all invocations of proot will have single namespace for all shared file descriptors and will be compatible with termux-x11.
Currently termux-x11 must be started inside proot-distro to let programs inside distro to let programs inside distro use MIT-SHM which is not very convenient and counter-intuitive.
Also on some firmwares proot distro does not find all pathes needed for termux-x11 so linking fails. I want to implement dropping tracer for the case of running inside proot, but in this case MIT-SHM becomes a big pain in the a$$.

**Comment by michalbednarski** [comment]
I guess I could try implementing integration if you'd make `libandroid-shm` side of implementation (could be side branch for now until I'd be able to confirm it is what I'd need, but won't be able to say for sure until I implement `proot` part)

**Comment by twaik** [comment]
As you can see currently libandroid-shmem (before Max's PR) `shmat` [implementation](https://github.com/termux/libandroid-shmem/blob/2fb093bc1cddf93f4b28d6a8e4ab2e2185e1c4a5/shmem.c#L432-L465) obtains fd and returns `mmap`'ed memory fragment. We could simply strip the `mmap` part and return file descriptor instead of it. In this case you will be able to pass it to tracees.
It is the thing you can do locally.

**Comment by twaik** [comment]
I mean instead of this
<details>

```
void* shmat(int shmid, void const* shmaddr, int shmflg)
{
	ashv_check_pid();

	int socket_id = ashv_socket_id_from_shmid(shmid);
	void *addr;

	pthread_mutex_lock(&mutex);

	int idx = ashv_find_local_index(shmid);
	if (idx == -1 && socket_id != ashv_local_socket_id) {
		idx = ashv_read_remote_segment(shmid);
	}

	if (idx == -1) {
		DBG ("%s: shmid %x does not exist", __PRETTY_FUNCTION__, shmid);
		pthread_mutex_unlock(&mutex);
		errno = EINVAL;
		return (void*) -1;
	}

	if (shmem[idx].addr == NULL) {
		shmem[idx].addr = mmap((void*) shmaddr, shmem[idx].size, PROT_READ | (shmflg == 0 ? PROT_WRITE : 0), MAP_SHARED, shmem[idx].descriptor, 0);
		if (shmem[idx].addr == MAP_FAILED) {
			DBG ("%s: mmap() failed for ID %x FD %d: %s", __PRETTY_FUNCTION__, idx, shmem[idx].descriptor, strerror(errno));
			shmem[idx].addr = NULL;
		}
	}
	addr = shmem[idx].addr;
	DBG ("%s: mapped addr %p for FD %d ID %d", __PRETTY_FUNCTION__, addr, shmem[idx].descriptor, idx);
	pthread_mutex_unlock (&mutex);

	return addr ? addr : (void *)-1;
}
```
</details>

You will have this
<details>

```
int shmat_fd(int shmid, void const* shmaddr, int shmflg)
{
	ashv_check_pid();

	int socket_id = ashv_socket_id_from_shmid(shmid);

	pthread_mutex_lock(&mutex);

	int idx = ashv_find_local_index(shmid);
	if (idx == -1 && socket_id != ashv_local_socket_id) {
		idx = ashv_read_remote_segment(shmid);
	}

	if (idx == -1) {
		DBG ("%s: shmid %x does not exist", __PRETTY_FUNCTION__, shmid);
		pthread_mutex_unlock(&mutex);
		errno = EINVAL;
		return -1;
	}

	pthread_mutex_unlock (&mutex);
	return shmem[idx].descriptor;
}
```
</details>
Or something similar.

**Comment by michalbednarski** [comment]
Ok, I'll try implementing something and see if I get somewhere

**Comment by michalbednarski** [comment]
Pushed initial version

This is still only minimally tested

To use new version from new branch has to be compiled with `PROOT_WITH_LIBANDROID_SHMEM=1` set in `make` arguments or env, in that build when `--sysvipc` is used then `shmget`/`shmat` is shared with `libandroid-shmem` unless `PROOT_DONT_SHARE_LIBANDROID_SHMEM` is set in environment when starting PRoot

**Comment by michalbednarski** [comment]
.deb can be downloaded from CI from https://github.com/termux/termux-packages/pull/23167

**Comment by twaik** [comment]
A very basic example
```
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/extensions/XShm.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <stdlib.h>
#include <unistd.h>

int main() {
    Display *d = XOpenDisplay(NULL);
    int s = DefaultScreen(d);
    Window w = XCreateSimpleWindow(d, RootWindow(d, s), 0, 0, 200, 200, 0, 0, WhitePixel(d, s));
    XMapWindow(d, w);
    XShmSegmentInfo si;
    XImage *i = XShmCreateImage(d, DefaultVisual(d, s), DefaultDepth(d, s), ZPixmap, NULL, &si, 200, 200);
    si.shmid = shmget(IPC_PRIVATE, i->bytes_per_line * i->height, IPC_CREAT | 0666);
    si.shmaddr = (char*)shmat(si.shmid, NULL, 0);
    i->data = si.shmaddr;
    si.readOnly = False;
    XShmAttach(d, &si);
    for (int y = 0; y < 200; y++) {
        for (int x = 0; x < 200; x++) {
            long p = y * i->bytes_per_line + x * 4;
            i->data[p + 0] = 0;
            i->data[p + 1] = 0;
            i->data[p + 2] = 255;
            i->data[p + 3] = 0;
        }
    }
    XShmPutImage(d, w, DefaultGC(d, s), i, 0, 0, 0, 0, 200, 200, False);
    XFlush(d);
    sleep(5);
    XShmDetach(d, &si);
    shmdt(si.shmaddr);
    shmctl(si.shmid, IPC_RMID, 0);
    XDestroyImage(i);
    XCloseDisplay(d);
    return 0;
}
```
It should be compiled like `clang -o e e.c -lX11 -lXext` (+ `-landroid-shmem` in termux). In termux it works fine and creates a window with red rectangle. With regular proot version it creates empty window with white background (probably default color of X11 window, not sure about it). In this new version of proot this program just crashes.
I checked it in proot-distro's debian launched like `proot-distro login --shared-tmp debian`. (`--shared-tmp` is needed to access `termux-x11`'s socket).
